### ISSUE TITLE
Can't see any styles on debug mode (non headless and devtools)

### ISSUE THREAD

**Issue by Richacinas** [Studiosity/grover#11]
Hi there,

While trying to debug some issues with the HTML that I'm converting to PDF using the Grover Middleware, I turned on the debug configuration so the HTML opens on Chromium with Devtools.

The problem is, that all the styles that I try to inspect are empty. I have my CSS stylesheets inside the head tag and they are loading perfectly.

I attach a screenshot so maybe we can find out if this is an issue that would belong here or not.

Thanks a lot!

![Captura de pantalla de 2019-04-23 14-08-46](https://user-images.githubusercontent.com/7046504/56579965-c76eac00-65d1-11e9-9ef7-ba5cd4377603.png)

**Comment by Richacinas** [comment]
I would like to add that, there are 2 tabs opened. The first one is blank.

**Comment by abrom** [comment]
It looks like your styles are loading/rendering ok?? Grover is really just a bunch of wrappers for calling out to Puppeteer (which in turn wraps the Chromium libraries). By the time you're getting to debugging things as you are in Chromium, it's more of an upstream type issue. I'd suggest raising the issue with either https://github.com/GoogleChrome/puppeteer or possibly https://github.com/chromium/chromium

I have seen that issue before when debugging in Chrome but usually clicking on another element and clicking back again resolves it. Can't say I've ever been able to reproduce it though :/

**Comment by Richacinas** [comment]
Yeah.. I think that you are right because at the moment I arrived to Chromium with the HTML and CSS loaded, it should be an issue on that side... Just wanted to make sure that it is not a problem with how we launch puppeteer or something like that.

Thanks

**Comment by abrom** [comment]
Ok.. so I take it back. I can replicate the issue with a super cut back version of what Grover essentially uses:
```
const puppeteer = require('puppeteer');

(async () => {
  let browser;
  try {
    const html = '<html><body><div style="color: blue">Hello there</div></body></html>';
    browser = await puppeteer.launch({ headless: false, devtools: true, slowMo: 5000 });
    const page = await browser.newPage();
    await page.setRequestInterception(true);
    page.once('request', request => {
      request.respond({ body: html });
      page.on('request', request => request.continue());
    });
    await page.goto('http://example.com', { waitUntil: 'networkidle0' });
  } finally {
    await browser.close();
  }
})();
```

If I add some sort of network call (ie an external script or link tag) to the HTML then it 'works' as expected. Alternatively, if the `waitUntil` is changed to `networkidle2` it also works as expected.

I'll need to check to see if there is any drawback to using `networkidle2`, but that would appear to get around the problem.

I still think that there is an issue (ie running the above script..) Most likely something to do with the `page.goto` call and it blocking waiting for the `networkidle0` event (which never happens because there are no network events if you don't have external scripts/styles in your HTML)

**Comment by abrom** [comment]
This issue in puppeteer seems like it's related: https://github.com/GoogleChrome/puppeteer/issues/3471

I've tested the above script with `puppeteer@next` as well with:

```
Grover.new(
  '<html><body><div style="color: blue">Hello there</div></body></html>',
  debug: { devtools: true, headless: false }, display_url: 'http://foo.test'
).to_pdf
```

Both of which weren't working (showing the styles) with puppeteer 1.14.0 but do with 1.14.0-next.

Win! Hopefully it won't be too much longer until 1.15 is released, but you would use 1.14.0-next if you're feeling adventurous!?

**Comment by Richacinas** [comment]
Great to know @abrom !!

Thanks so much for the research. If I need to do some serious debugging I will definetely install 1.14.0-next, but only for debugging purpose of course!

**Comment by Richacinas** [comment]
I tried today to update to `puppeteer@next`, and the problem still persists. Emtpy styles.

**Comment by abrom** [comment]
Can you confirm you stopped/restarted your rails server/console?

**Comment by Richacinas** [comment]
Yes I did.

**Comment by abrom** [comment]
Hi @Richacinas, sorry for the delayed reply. Were you able to resolve this? puppeteer 1.16 is out now so hopefully the network bug fix included.

**Comment by Richacinas** [comment]
Hi again @abrom.

No, this issue remained the same. I'm curious because you said that it worked for you with `puppeteer@next`, however that wasn't my case.

I didn't try to update the grover version because now I'm working on something else and I really can't do it.. I will try.

Thanks a lot

**Comment by abrom** [comment]
How have you been going with this issue @Richacinas  ?

FYI I've just released an update that may help by allowing you to specify the wait until option. See #32

**Comment by Richacinas** [comment]
Hi again.

I finally came back to this project, and tried with the latest version of Puppeteer just released 4 days ago (v3.0.0).

The issue still remains. I haven't set up any `wait_until` option, by the way.

**Comment by abrom** [comment]
I'd suggest you try out some of the different `wait_until` options.. if that doesn't work maybe look at adding the `page.waitFor` method? Maybe just start by hard-coding to a static `5000` (5 seconds). 

https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pagewaitforselectororfunctionortimeout-options-args

It's hard to really do much as I've no idea what your page is doing. If it's got JS code running to render the page content it's possible that this is taking too long and puppeteer is taking the screenshot too soon.

**Comment by jpgeek** [comment]
Hi, and thanks for all your work on this!  I think I am facing the same issue.  Using:
  grover-0.12.1
  puppeteer@3.0.2
  Chromium 81.0.4044.0
Not using the middleware 

Tried these variations on wat_until:
```
    timeout: 0, # Timeout in ms. A value of `0` means 'no timeout'. DEBUG!!
    #wait_until: 'networkidle2', # browser exits immediately
    #wait_until: 'networkidle0', # no styles displayed
    #wait_until: 'load', # browser exits immediately
    #wait_until: 'domcontentload', # no styles displayed
```
To no avail.

**Comment by abrom** [comment]
Hi @jpgeek, per comments above this would appear to be an issue with either Puppeteer or Chrome/Chromium. It's repeatable with a very simple NodeJS script, also posted above. Grover is a very thin wrapper to simply call to Puppeteer.

I'd suggest raising the issue with either https://github.com/GoogleChrome/puppeteer or possibly https://github.com/chromium/chromium

**Comment by jpgeek** [comment]
Hi @abrom and thanks for the quick reply.  I figured as much but thought I would throw it into the thread as a reply to your previous comment in case it is useful for others.

**Comment by nicolasrouanne** [comment]
For what it's worth, this did the trick for me ([source](https://stackoverflow.com/a/60736572/5186918)):
```css
html {
  -webkit-print-color-adjust: exact;
}
```

**Comment by rommguy** [comment]
There's an open issue for puppeteer on this - [5939](https://github.com/puppeteer/puppeteer/issues/5939)

**Comment by NJaff** [comment]
> For what it's worth, this did the trick for me ([source](https://stackoverflow.com/a/60736572/5186918)):
> 
> ```css
> html {
>   -webkit-print-color-adjust: exact;
> }
> ```

This worked perfectly. Thanks.
